services:
    nginx:
        image: nginx:1.26-alpine
        ports:
            - ${HOST_PORT:-1234}:80
        restart: always
        depends_on:
            - patomat2
            - patomat2-server
        environment:
            NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
            ROOT: ${ROOT:-/patomat2}
            ORIGIN: ${PUBLIC_URL:-http://localhost:${HOST_PORT:-1234}}
            PORT: ${PUBLIC_PORT:-''}
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
    patomat2-server:
        image: ghcr.io/onto-deside-vse/patomat2-backend:latest
        restart: always
        environment:
            PATOMAT2_CORSALLOWEDORIGINS: ${PUBLIC_URL:-http://localhost:${HOST_PORT:-1234}}
            PATOMAT2_NEWENTITYIRIBASE: ${NEW_ENTITY_IRI_BASE:-https://owl.vse.cz/patomat2/}
            SPRINGDOC_SWAGGER_UI_URL: ${ROOT}/service/server/v3/api-docs
            PATOMAT2_SECURITY_MAXSESSIONS: ${MAX_SESSIONS:-20}
        env_file:
            - .env
    patomat2:
        image: ghcr.io/onto-deside-vse/patomat2-frontend:latest
        restart: always
        depends_on:
            - patomat2-server
        environment:
            SERVER_URL: ${PUBLIC_URL:-http://localhost:${HOST_PORT:-1234}}${ROOT:-/patomat2}/service/server
            CONTEXT_PATH: ${ROOT:-/patomat2}
