services:
    nginx:
        image: nginx:1.26-alpine
        ports:
            - ${HOST_PORT:-1234}:80
        restart: always
        depends_on:
            - patomat2
            - patomat2-server
        environment:
            NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
            ROOT: ${ROOT}
            ORIGIN: ${URL}
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
    patomat2-server:
        build:
            context: backend
            dockerfile: Dockerfile
        restart: always
        ports:
            -   8080:8080
        environment:
            PATOMAT2_CORSALLOWEDORIGINS: ${URL}
    patomat2:
        build:
            context: frontend
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - patomat2-server
        ports:
            -   3000:80
        environment:
            SERVER_URL: ${URL}${ROOT}/service/server
            CONTEXT_PATH: ${ROOT}
