services:
    nginx:
        image: nginx:1.26-alpine
        ports:
            - ${HOST_PORT:-1234}:80
        restart: always
        depends_on:
            - patomat2
            - patomat2-server
        environment:
            NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
            ROOT: ${ROOT:-/patomat2}
            ORIGIN: ${PUBLIC_URL:-http://localhost:${HOST_PORT:-1234}}
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
    patomat2-server:
        build:
            context: backend
            dockerfile: Dockerfile
        restart: always
        environment:
            PATOMAT2_CORSALLOWEDORIGINS: ${PUBLIC_URL:-http://localhost:${HOST_PORT:-1234}}
    patomat2:
        build:
            context: frontend
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - patomat2-server
        environment:
            SERVER_URL: ${PUBLIC_URL:-http://localhost:${HOST_PORT:-1234}}${ROOT:-/patomat2}/service/server
            CONTEXT_PATH: ${ROOT:-/patomat2}
