spring:
    application:
        name: PatOMat2
    servlet:
        multipart:
            max-request-size: 12MB
            max-file-size: 10MB
    ai:
        model:
            chat: "ollama"
        ollama:
            base-url:
            chat:
                options:
                    model: llama-3.3-70b-instruct:q4
                    keep-alive: 1m
                    num-ctx: 4096

patomat2:
    storage: data
    cors-allowed-origins: http://localhost:5173
    new-entity-iri-base: https://owl.vse.cz/patomat2/
    security:
        max-sessions: 20
server:
    servlet:
        context-path: /patomat2
    port: 8080
    forward-headers-strategy: framework

logging:
    level:
        cz.vse.swoe.ontodeside.patomat2: TRACE
        org.springframework: INFO

springdoc:
    swagger-ui:
        path: /swagger-ui
        url: /v3/api-docs
        disable-swagger-default-url: true
