spring:
    application:
        name: PatOMat2
    servlet:
        multipart:
            max-request-size: 12MB
            max-file-size: 10MB

patomat2:
    storage: data
    cors-allowed-origins: http://localhost:5173
    new-entity-iri-base: https://owl.vse.cz/patomat2/
    security:
        max-sessions: 20
server:
    servlet:
        context-path: /patomat2
    port: 8080

logging:
    level:
        cz.cvut.kbss.ontodeside.patomat2: TRACE
        org.springframework: INFO
