spring:
    application:
        name: PatOMat2

patomat2:
    storage: data
server:
    servlet:
        context-path: /patomat2
    port: 8080

logging:
    level:
      cz.cvut.kbss.ontodeside.patomat2: TRACE
      org.springframework: INFO
